global:
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: quickstart-quickstart-informatica-powercenter
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - eu-central-1
    - eu-west-1
    - sa-east-1
    - us-east-1
    - us-west-1
    - us-west-2
  reporting: true
 
tests:
  quickstart-quickstart-informatica-powercentert1:
    parameter_input: quickstart-quickstart-informatica-powercenter-example-params1.json
    template_file: quickstart-quickstart-informatica-powercenter-example1.template
  quickstart-quickstart-informatica-powercentert2:
    parameter_input: quickstart-quickstart-informatica-powercenter-example-params2.json
    template_file: quickstart-quickstart-informatica-powercenter-example2.template
